//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 01:31:46 PM CET 
//


package it.polito.dp2.RNS.sol1.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.RNS.sol1.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.RNS.sol1.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlaceItem }
     * 
     */
    public PlaceItem createPlaceItem() {
        return new PlaceItem();
    }

    /**
     * Create an instance of {@link Roads }
     * 
     */
    public Roads createRoads() {
        return new Roads();
    }

    /**
     * Create an instance of {@link Rns }
     * 
     */
    public Rns createRns() {
        return new Rns();
    }

    /**
     * Create an instance of {@link EntityItem }
     * 
     */
    public EntityItem createEntityItem() {
        return new EntityItem();
    }

    /**
     * Create an instance of {@link ConnectionItem }
     * 
     */
    public ConnectionItem createConnectionItem() {
        return new ConnectionItem();
    }

    /**
     * Create an instance of {@link VehicleItem }
     * 
     */
    public VehicleItem createVehicleItem() {
        return new VehicleItem();
    }

    /**
     * Create an instance of {@link SegmentItem }
     * 
     */
    public SegmentItem createSegmentItem() {
        return new SegmentItem();
    }

    /**
     * Create an instance of {@link PlaceItem.ParkingArea }
     * 
     */
    public PlaceItem.ParkingArea createPlaceItemParkingArea() {
        return new PlaceItem.ParkingArea();
    }

    /**
     * Create an instance of {@link Roads.Road }
     * 
     */
    public Roads.Road createRoadsRoad() {
        return new Roads.Road();
    }

}
