//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 01:31:46 PM CET 
//


package it.polito.dp2.RNS.sol1.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlaceItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlaceItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="roadSegment" type="{}SegmentItem"/>
 *         &lt;element name="parkingArea">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="services" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="gate" type="{}GateItem"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="capacity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlaceItem", propOrder = {
    "roadSegment",
    "parkingArea",
    "gate"
})
public class PlaceItem {

    protected SegmentItem roadSegment;
    protected PlaceItem.ParkingArea parkingArea;
    @XmlSchemaType(name = "string")
    protected GateItem gate;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "capacity", required = true)
    protected BigInteger capacity;

    /**
     * Gets the value of the roadSegment property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentItem }
     *     
     */
    public SegmentItem getRoadSegment() {
        return roadSegment;
    }

    /**
     * Sets the value of the roadSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentItem }
     *     
     */
    public void setRoadSegment(SegmentItem value) {
        this.roadSegment = value;
    }

    /**
     * Gets the value of the parkingArea property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceItem.ParkingArea }
     *     
     */
    public PlaceItem.ParkingArea getParkingArea() {
        return parkingArea;
    }

    /**
     * Sets the value of the parkingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceItem.ParkingArea }
     *     
     */
    public void setParkingArea(PlaceItem.ParkingArea value) {
        this.parkingArea = value;
    }

    /**
     * Gets the value of the gate property.
     * 
     * @return
     *     possible object is
     *     {@link GateItem }
     *     
     */
    public GateItem getGate() {
        return gate;
    }

    /**
     * Sets the value of the gate property.
     * 
     * @param value
     *     allowed object is
     *     {@link GateItem }
     *     
     */
    public void setGate(GateItem value) {
        this.gate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCapacity(BigInteger value) {
        this.capacity = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="services" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "services"
    })
    public static class ParkingArea {

        protected List<String> services;

        /**
         * Gets the value of the services property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the services property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServices().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getServices() {
            if (services == null) {
                services = new ArrayList<String>();
            }
            return this.services;
        }

    }

}
